# Site settings
title:       Joe Masilotti
email:       joseph.masilotti@gmail.com
author:      Joe Masilotti
description: "Joe Masilotti"
baseurl:     ""
url:         "http://joemasilotti.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: joemasilotti
stackoverflow_id: 384110
twitter_username: joemasilotti
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     2
sass:
  compressed: true
